repos:
    - repo: https://github.com/ambv/black
      rev: 22.6.0
      hooks:
          - id: black
            language_version: python3
    - repo: https://github.com/timothycrosley/isort
      rev: 5.10.1
      hooks:
          - id: isort
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-added-large-files
          - id: trailing-whitespace
          - id: debug-statements
    - repo: git://github.com/doublify/pre-commit-clang-format
      rev: 62302476d0da01515660132d76902359bed0f782
      hooks:
          - id: clang-format
