#!/bin/bash

export CMAKE_PREFIX_PATH="/c/Program Files"
export CMAKE_GENERATOR="Visual Studio 15 2017 Win64"

curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp \
    INSTALL_PREFIX="/c/Program Files/logaddexp" bash

curl -fsSL https://git.io/JerYI | GITHUB_USER=limix GITHUB_PROJECT=liknorm \
    INSTALL_PREFIX="/c/Program Files/liknorm" bash
