name: Test it using poetry

on: [push, pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2022]

    steps:
      - uses: actions/checkout@v3

      - name: Test it
        run: |
          pipx install poetry==1.2.0b3
          poetry install
          poetry run pytest
